eagle:
  #扫描eagle服务，多个包用逗号分隔
  base-package: eagle.jfaster.org.service

  #注册中心配置，可以配置多个
  registry:
    - name: regCenter
      protocol: zookeeper
      address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
      namespace: eagle
      base-sleep-time-milliseconds: 1000
      max-sleep-time-milliseconds: 3000
      max-retries: 3

  #协议配置，可以配置多个
  protocol:
    - id: proto
      name: eagle
      serialization: kryo
      use-default: true
      max-content-length: 16777216
      max-server-connection: 20000
      core-worker-thread: 20
      max-worker-thread: 400
      worker-queue-size: 10
      cluster: eagle

  #baseRefer配置，可以配置多个
  base-refer:
    - id: baseRefer
      request-timeout: 300
      actives: 20000
      actives-wait: 300
      loadbalance: roundrobin
      ha-strategy: failfast
      compress: false
      group: eagleGroup
      connect-timeout: 10000
      protocol: proto
      registry: regCenter

  #baseService配置，可以配置多个
  base-service:
    - id: baseService
      group: eagleGroup
      export: proto:9200
      registry: regCenter